# Generated by Django 4.0.5 on 2022-07-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
