# Generated by Django 4.0.5 on 2022-08-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_good',
            field=models.BooleanField(default=False),
        ),
    ]
